services:
  db:
    image: postgres:15
    container_name: tienda_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tienda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:   
    build: ./backend
    container_name: tienda_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data: